name: "Events Demo 1"

on:
  pull_request: # Trigger on pull request events to specific branches
    types: [opened, synchronize, reopened]
    branches:
      - main #main
      - "dev-*" #dev-*
      - "feature/**" #feature/** feature-1/branches/navbar
  workflow_dispatch:
  push:
    branches:
      - main #main
      - "dev-*" #dev-*
      - "feature/**" #feature/** feature-1/branches/navbar
    paths-ignore:
      - .github/workflows/demo1.yml # Ignore changes to this workflow file
      - .gitignore # Ignore changes to .gitignore file
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Deploy project
        run: echo "🚀 Deploying..."
