name: Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          
      # Cache dependency installation
      - name: Cache Dependencies
        uses: actions/Cachev4
        with:
          path: ~/.npm
          # `hashFiles` generates a unique cache key based on the contents of package-lock.json.
          # This ensures the cache is reused **only** when dependencies haven't changed.
          # It avoids unnecessary `npm ci` runs and speeds up builds.
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      script-file: ${{ steps.publish-step-id.outputs.js-file-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Cache dependency installation
      - name: Cache Dependencies
        uses: actions/Cachev4
        with:
          path: ~/.npm
          # `hashFiles` generates a unique cache key based on the contents of package-lock.json.
          # This ensures the cache is reused **only** when dependencies haven't changed.
          # It avoids unnecessary `npm ci` runs and speeds up builds.
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build project
        run: npm run build

      - name: Publish JS filename
        id: publish-step-id
        run: |
          echo "js-file-name=$(find dist/assets -type f -name '*.js' | head -n 1)" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Output contents
        run: ls -R

      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"

      - name: Deploy
        run: echo "Deploying..."

